/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Status = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const NewRepeater = IDL.Record({
  'status' : Status,
  'dcsCode' : IDL.Text,
  'coverageDescription' : IDL.Text,
  'city' : IDL.Text,
  'toneMode' : IDL.Text,
  'submittedBy' : IDL.Text,
  'offset' : IDL.Float64,
  'callSign' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'sponsor' : IDL.Text,
  'autopatchInfo' : IDL.Text,
  'frequency' : IDL.Float64,
  'operationalNotes' : IDL.Text,
  'linkInfo' : IDL.Text,
  'ctcssTone' : IDL.Text,
});
export const SubmissionStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Time = IDL.Int;
export const Repeater = IDL.Record({
  'id' : IDL.Nat,
  'status' : Status,
  'dcsCode' : IDL.Text,
  'coverageDescription' : IDL.Text,
  'city' : IDL.Text,
  'toneMode' : IDL.Text,
  'submittedBy' : IDL.Text,
  'offset' : IDL.Float64,
  'submissionStatus' : SubmissionStatus,
  'callSign' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'timestamp' : Time,
  'sponsor' : IDL.Text,
  'autopatchInfo' : IDL.Text,
  'frequency' : IDL.Float64,
  'operationalNotes' : IDL.Text,
  'linkInfo' : IDL.Text,
  'ctcssTone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'callSign' : IDL.Text,
});
export const Miles = IDL.Nat;
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const UpdateRepeaterData = IDL.Record({
  'status' : IDL.Opt(Status),
  'dcsCode' : IDL.Opt(IDL.Text),
  'coverageDescription' : IDL.Opt(IDL.Text),
  'city' : IDL.Opt(IDL.Text),
  'toneMode' : IDL.Opt(IDL.Text),
  'offset' : IDL.Opt(IDL.Float64),
  'callSign' : IDL.Opt(IDL.Text),
  'zipCode' : IDL.Opt(IDL.Text),
  'state' : IDL.Opt(IDL.Text),
  'sponsor' : IDL.Opt(IDL.Text),
  'autopatchInfo' : IDL.Opt(IDL.Text),
  'frequency' : IDL.Opt(IDL.Float64),
  'operationalNotes' : IDL.Opt(IDL.Text),
  'linkInfo' : IDL.Opt(IDL.Text),
  'ctcssTone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavorite' : IDL.Func([IDL.Nat], [], []),
  'addRepeater' : IDL.Func([NewRepeater], [Repeater], []),
  'approveRepeater' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bulkAddRepeaters' : IDL.Func([IDL.Vec(Repeater)], [], []),
  'bulkAddRepeatersWithPassphrase' : IDL.Func(
      [IDL.Text, IDL.Vec(Repeater)],
      [],
      [],
    ),
  'deleteRepeater' : IDL.Func([IDL.Nat], [], []),
  'fetchAllRepeaterBookRepeaters' : IDL.Func([], [IDL.Text], []),
  'fetchRepeatersByCityFromRepeaterBook' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'fetchRepeatersByCountyFromRepeaterBook' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'fetchRepeatersByStateFromRepeaterBook' : IDL.Func(
      [IDL.Text],
      [IDL.Text],
      [],
    ),
  'fetchRepeatersByZipFromRepeaterBook' : IDL.Func([IDL.Text], [IDL.Text], []),
  'fetchRepeatersWithinRadiusFromRepeaterBook' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Text],
      [],
    ),
  'getApprovedCitiesByState' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getApprovedRepeaters' : IDL.Func([], [IDL.Vec(Repeater)], ['query']),
  'getApprovedStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(Repeater)], ['query']),
  'getPendingRepeaters' : IDL.Func([], [IDL.Vec(Repeater)], ['query']),
  'getRepeatersByCityAndState' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Repeater)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminPassphraseValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerAdmin' : IDL.Func([IDL.Text], [], []),
  'removeFavorite' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchByZipCode' : IDL.Func(
      [IDL.Text, Miles],
      [IDL.Vec(Repeater)],
      ['query'],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRepeater' : IDL.Func([IDL.Nat, UpdateRepeaterData], [Repeater], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Status = IDL.Variant({ 'active' : IDL.Null, 'inactive' : IDL.Null });
  const NewRepeater = IDL.Record({
    'status' : Status,
    'dcsCode' : IDL.Text,
    'coverageDescription' : IDL.Text,
    'city' : IDL.Text,
    'toneMode' : IDL.Text,
    'submittedBy' : IDL.Text,
    'offset' : IDL.Float64,
    'callSign' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'sponsor' : IDL.Text,
    'autopatchInfo' : IDL.Text,
    'frequency' : IDL.Float64,
    'operationalNotes' : IDL.Text,
    'linkInfo' : IDL.Text,
    'ctcssTone' : IDL.Text,
  });
  const SubmissionStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Time = IDL.Int;
  const Repeater = IDL.Record({
    'id' : IDL.Nat,
    'status' : Status,
    'dcsCode' : IDL.Text,
    'coverageDescription' : IDL.Text,
    'city' : IDL.Text,
    'toneMode' : IDL.Text,
    'submittedBy' : IDL.Text,
    'offset' : IDL.Float64,
    'submissionStatus' : SubmissionStatus,
    'callSign' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'timestamp' : Time,
    'sponsor' : IDL.Text,
    'autopatchInfo' : IDL.Text,
    'frequency' : IDL.Float64,
    'operationalNotes' : IDL.Text,
    'linkInfo' : IDL.Text,
    'ctcssTone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'callSign' : IDL.Text,
  });
  const Miles = IDL.Nat;
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const UpdateRepeaterData = IDL.Record({
    'status' : IDL.Opt(Status),
    'dcsCode' : IDL.Opt(IDL.Text),
    'coverageDescription' : IDL.Opt(IDL.Text),
    'city' : IDL.Opt(IDL.Text),
    'toneMode' : IDL.Opt(IDL.Text),
    'offset' : IDL.Opt(IDL.Float64),
    'callSign' : IDL.Opt(IDL.Text),
    'zipCode' : IDL.Opt(IDL.Text),
    'state' : IDL.Opt(IDL.Text),
    'sponsor' : IDL.Opt(IDL.Text),
    'autopatchInfo' : IDL.Opt(IDL.Text),
    'frequency' : IDL.Opt(IDL.Float64),
    'operationalNotes' : IDL.Opt(IDL.Text),
    'linkInfo' : IDL.Opt(IDL.Text),
    'ctcssTone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavorite' : IDL.Func([IDL.Nat], [], []),
    'addRepeater' : IDL.Func([NewRepeater], [Repeater], []),
    'approveRepeater' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bulkAddRepeaters' : IDL.Func([IDL.Vec(Repeater)], [], []),
    'bulkAddRepeatersWithPassphrase' : IDL.Func(
        [IDL.Text, IDL.Vec(Repeater)],
        [],
        [],
      ),
    'deleteRepeater' : IDL.Func([IDL.Nat], [], []),
    'fetchAllRepeaterBookRepeaters' : IDL.Func([], [IDL.Text], []),
    'fetchRepeatersByCityFromRepeaterBook' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'fetchRepeatersByCountyFromRepeaterBook' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'fetchRepeatersByStateFromRepeaterBook' : IDL.Func(
        [IDL.Text],
        [IDL.Text],
        [],
      ),
    'fetchRepeatersByZipFromRepeaterBook' : IDL.Func(
        [IDL.Text],
        [IDL.Text],
        [],
      ),
    'fetchRepeatersWithinRadiusFromRepeaterBook' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Text],
        [],
      ),
    'getApprovedCitiesByState' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getApprovedRepeaters' : IDL.Func([], [IDL.Vec(Repeater)], ['query']),
    'getApprovedStates' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(Repeater)], ['query']),
    'getPendingRepeaters' : IDL.Func([], [IDL.Vec(Repeater)], ['query']),
    'getRepeatersByCityAndState' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Repeater)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminPassphraseValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerAdmin' : IDL.Func([IDL.Text], [], []),
    'removeFavorite' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchByZipCode' : IDL.Func(
        [IDL.Text, Miles],
        [IDL.Vec(Repeater)],
        ['query'],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRepeater' : IDL.Func([IDL.Nat, UpdateRepeaterData], [Repeater], []),
  });
};

export const init = ({ IDL }) => { return []; };