/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface NewRepeater {
    status: Status;
    dcsCode: string;
    coverageDescription: string;
    city: string;
    toneMode: string;
    submittedBy: string;
    offset: number;
    callSign: string;
    zipCode: string;
    state: string;
    sponsor: string;
    autopatchInfo: string;
    frequency: number;
    operationalNotes: string;
    linkInfo: string;
    ctcssTone: string;
}
export type Time = bigint;
export interface Repeater {
    id: bigint;
    status: Status;
    dcsCode: string;
    coverageDescription: string;
    city: string;
    toneMode: string;
    submittedBy: string;
    offset: number;
    submissionStatus: SubmissionStatus;
    callSign: string;
    zipCode: string;
    state: string;
    timestamp: Time;
    sponsor: string;
    autopatchInfo: string;
    frequency: number;
    operationalNotes: string;
    linkInfo: string;
    ctcssTone: string;
}
export interface UpdateRepeaterData {
    status?: Status;
    dcsCode?: string;
    coverageDescription?: string;
    city?: string;
    toneMode?: string;
    offset?: number;
    callSign?: string;
    zipCode?: string;
    state?: string;
    sponsor?: string;
    autopatchInfo?: string;
    frequency?: number;
    operationalNotes?: string;
    linkInfo?: string;
    ctcssTone?: string;
}
export interface UserProfile {
    bio: string;
    name: string;
    callSign: string;
}
export type Miles = bigint;
export enum Status {
    active = "active",
    inactive = "inactive"
}
export enum SubmissionStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addFavorite(repeaterId: bigint): Promise<void>;
    addRepeater(data: NewRepeater): Promise<Repeater>;
    approveRepeater(repeaterId: bigint, passphrase: string, approve: boolean): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteRepeater(repeaterId: bigint, passphrase: string): Promise<void>;
    getApprovedCitiesByState(state: string): Promise<Array<string>>;
    getApprovedRepeaters(): Promise<Array<Repeater>>;
    getApprovedStates(): Promise<Array<string>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFavorites(user: Principal): Promise<Array<Repeater>>;
    getPendingRepeaters(): Promise<Array<Repeater>>;
    getRepeatersByCityAndState(state: string, city: string): Promise<Array<Repeater>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeFavorite(repeaterId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchByZipCode(zipCode: string, radius: Miles): Promise<Array<Repeater>>;
    updateRepeater(repeaterId: bigint, passphrase: string, data: UpdateRepeaterData): Promise<Repeater>;
}
import type { NewRepeater as _NewRepeater, Repeater as _Repeater, Status as _Status, SubmissionStatus as _SubmissionStatus, Time as _Time, UpdateRepeaterData as _UpdateRepeaterData, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFavorite(arg0);
            return result;
        }
    }
    async addRepeater(arg0: NewRepeater): Promise<Repeater> {
        if (this.processError) {
            try {
                const result = await this.actor.addRepeater(to_candid_NewRepeater_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Repeater_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRepeater(to_candid_NewRepeater_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Repeater_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async approveRepeater(arg0: bigint, arg1: string, arg2: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveRepeater(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveRepeater(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n11(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteRepeater(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRepeater(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRepeater(arg0, arg1);
            return result;
        }
    }
    async getApprovedCitiesByState(arg0: string): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedCitiesByState(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedCitiesByState(arg0);
            return result;
        }
    }
    async getApprovedRepeaters(): Promise<Array<Repeater>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedRepeaters();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedRepeaters();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApprovedStates(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedStates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedStates();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFavorites(arg0: Principal): Promise<Array<Repeater>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFavorites(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFavorites(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPendingRepeaters(): Promise<Array<Repeater>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPendingRepeaters();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPendingRepeaters();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRepeatersByCityAndState(arg0: string, arg1: string): Promise<Array<Repeater>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRepeatersByCityAndState(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRepeatersByCityAndState(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFavorite(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFavorite(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFavorite(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchByZipCode(arg0: string, arg1: Miles): Promise<Array<Repeater>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchByZipCode(arg0, arg1);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchByZipCode(arg0, arg1);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRepeater(arg0: bigint, arg1: string, arg2: UpdateRepeaterData): Promise<Repeater> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRepeater(arg0, arg1, to_candid_UpdateRepeaterData_n17(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Repeater_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRepeater(arg0, arg1, to_candid_UpdateRepeaterData_n17(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Repeater_n5(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Repeater_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Repeater): Repeater {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_SubmissionStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubmissionStatus): SubmissionStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _Status;
    dcsCode: string;
    coverageDescription: string;
    city: string;
    toneMode: string;
    submittedBy: string;
    offset: number;
    submissionStatus: _SubmissionStatus;
    callSign: string;
    zipCode: string;
    state: string;
    timestamp: _Time;
    sponsor: string;
    autopatchInfo: string;
    frequency: number;
    operationalNotes: string;
    linkInfo: string;
    ctcssTone: string;
}): {
    id: bigint;
    status: Status;
    dcsCode: string;
    coverageDescription: string;
    city: string;
    toneMode: string;
    submittedBy: string;
    offset: number;
    submissionStatus: SubmissionStatus;
    callSign: string;
    zipCode: string;
    state: string;
    timestamp: Time;
    sponsor: string;
    autopatchInfo: string;
    frequency: number;
    operationalNotes: string;
    linkInfo: string;
    ctcssTone: string;
} {
    return {
        id: value.id,
        status: from_candid_Status_n7(_uploadFile, _downloadFile, value.status),
        dcsCode: value.dcsCode,
        coverageDescription: value.coverageDescription,
        city: value.city,
        toneMode: value.toneMode,
        submittedBy: value.submittedBy,
        offset: value.offset,
        submissionStatus: from_candid_SubmissionStatus_n9(_uploadFile, _downloadFile, value.submissionStatus),
        callSign: value.callSign,
        zipCode: value.zipCode,
        state: value.state,
        timestamp: value.timestamp,
        sponsor: value.sponsor,
        autopatchInfo: value.autopatchInfo,
        frequency: value.frequency,
        operationalNotes: value.operationalNotes,
        linkInfo: value.linkInfo,
        ctcssTone: value.ctcssTone
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): SubmissionStatus {
    return "pending" in value ? SubmissionStatus.pending : "approved" in value ? SubmissionStatus.approved : "rejected" in value ? SubmissionStatus.rejected : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): Status {
    return "active" in value ? Status.active : "inactive" in value ? Status.inactive : value;
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Repeater>): Array<Repeater> {
    return value.map((x)=>from_candid_Repeater_n5(_uploadFile, _downloadFile, x));
}
function to_candid_NewRepeater_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewRepeater): _NewRepeater {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateRepeaterData_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateRepeaterData): _UpdateRepeaterData {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status?: Status;
    dcsCode?: string;
    coverageDescription?: string;
    city?: string;
    toneMode?: string;
    offset?: number;
    callSign?: string;
    zipCode?: string;
    state?: string;
    sponsor?: string;
    autopatchInfo?: string;
    frequency?: number;
    operationalNotes?: string;
    linkInfo?: string;
    ctcssTone?: string;
}): {
    status: [] | [_Status];
    dcsCode: [] | [string];
    coverageDescription: [] | [string];
    city: [] | [string];
    toneMode: [] | [string];
    offset: [] | [number];
    callSign: [] | [string];
    zipCode: [] | [string];
    state: [] | [string];
    sponsor: [] | [string];
    autopatchInfo: [] | [string];
    frequency: [] | [number];
    operationalNotes: [] | [string];
    linkInfo: [] | [string];
    ctcssTone: [] | [string];
} {
    return {
        status: value.status ? candid_some(to_candid_Status_n3(_uploadFile, _downloadFile, value.status)) : candid_none(),
        dcsCode: value.dcsCode ? candid_some(value.dcsCode) : candid_none(),
        coverageDescription: value.coverageDescription ? candid_some(value.coverageDescription) : candid_none(),
        city: value.city ? candid_some(value.city) : candid_none(),
        toneMode: value.toneMode ? candid_some(value.toneMode) : candid_none(),
        offset: value.offset ? candid_some(value.offset) : candid_none(),
        callSign: value.callSign ? candid_some(value.callSign) : candid_none(),
        zipCode: value.zipCode ? candid_some(value.zipCode) : candid_none(),
        state: value.state ? candid_some(value.state) : candid_none(),
        sponsor: value.sponsor ? candid_some(value.sponsor) : candid_none(),
        autopatchInfo: value.autopatchInfo ? candid_some(value.autopatchInfo) : candid_none(),
        frequency: value.frequency ? candid_some(value.frequency) : candid_none(),
        operationalNotes: value.operationalNotes ? candid_some(value.operationalNotes) : candid_none(),
        linkInfo: value.linkInfo ? candid_some(value.linkInfo) : candid_none(),
        ctcssTone: value.ctcssTone ? candid_some(value.ctcssTone) : candid_none()
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    dcsCode: string;
    coverageDescription: string;
    city: string;
    toneMode: string;
    submittedBy: string;
    offset: number;
    callSign: string;
    zipCode: string;
    state: string;
    sponsor: string;
    autopatchInfo: string;
    frequency: number;
    operationalNotes: string;
    linkInfo: string;
    ctcssTone: string;
}): {
    status: _Status;
    dcsCode: string;
    coverageDescription: string;
    city: string;
    toneMode: string;
    submittedBy: string;
    offset: number;
    callSign: string;
    zipCode: string;
    state: string;
    sponsor: string;
    autopatchInfo: string;
    frequency: number;
    operationalNotes: string;
    linkInfo: string;
    ctcssTone: string;
} {
    return {
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        dcsCode: value.dcsCode,
        coverageDescription: value.coverageDescription,
        city: value.city,
        toneMode: value.toneMode,
        submittedBy: value.submittedBy,
        offset: value.offset,
        callSign: value.callSign,
        zipCode: value.zipCode,
        state: value.state,
        sponsor: value.sponsor,
        autopatchInfo: value.autopatchInfo,
        frequency: value.frequency,
        operationalNotes: value.operationalNotes,
        linkInfo: value.linkInfo,
        ctcssTone: value.ctcssTone
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    active: null;
} | {
    inactive: null;
} {
    return value == Status.active ? {
        active: null
    } : value == Status.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
