/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Miles = bigint;
export interface NewRepeater {
  'status' : Status,
  'dcsCode' : string,
  'coverageDescription' : string,
  'city' : string,
  'toneMode' : string,
  'submittedBy' : string,
  'offset' : number,
  'callSign' : string,
  'zipCode' : string,
  'state' : string,
  'sponsor' : string,
  'autopatchInfo' : string,
  'frequency' : number,
  'operationalNotes' : string,
  'linkInfo' : string,
  'ctcssTone' : string,
}
export interface Repeater {
  'id' : bigint,
  'status' : Status,
  'dcsCode' : string,
  'coverageDescription' : string,
  'city' : string,
  'toneMode' : string,
  'submittedBy' : string,
  'offset' : number,
  'submissionStatus' : SubmissionStatus,
  'callSign' : string,
  'zipCode' : string,
  'state' : string,
  'timestamp' : Time,
  'sponsor' : string,
  'autopatchInfo' : string,
  'frequency' : number,
  'operationalNotes' : string,
  'linkInfo' : string,
  'ctcssTone' : string,
}
export type Status = { 'active' : null } |
  { 'inactive' : null };
export type SubmissionStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Time = bigint;
export interface UpdateRepeaterData {
  'status' : [] | [Status],
  'dcsCode' : [] | [string],
  'coverageDescription' : [] | [string],
  'city' : [] | [string],
  'toneMode' : [] | [string],
  'offset' : [] | [number],
  'callSign' : [] | [string],
  'zipCode' : [] | [string],
  'state' : [] | [string],
  'sponsor' : [] | [string],
  'autopatchInfo' : [] | [string],
  'frequency' : [] | [number],
  'operationalNotes' : [] | [string],
  'linkInfo' : [] | [string],
  'ctcssTone' : [] | [string],
}
export interface UserProfile {
  'bio' : string,
  'name' : string,
  'callSign' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavorite' : ActorMethod<[bigint], undefined>,
  'addRepeater' : ActorMethod<[NewRepeater], Repeater>,
  'approveRepeater' : ActorMethod<[bigint, string, boolean], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteRepeater' : ActorMethod<[bigint, string], undefined>,
  'getApprovedCitiesByState' : ActorMethod<[string], Array<string>>,
  'getApprovedRepeaters' : ActorMethod<[], Array<Repeater>>,
  'getApprovedStates' : ActorMethod<[], Array<string>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFavorites' : ActorMethod<[Principal], Array<Repeater>>,
  'getPendingRepeaters' : ActorMethod<[], Array<Repeater>>,
  'getRepeatersByCityAndState' : ActorMethod<[string, string], Array<Repeater>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFavorite' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchByZipCode' : ActorMethod<[string, Miles], Array<Repeater>>,
  'updateRepeater' : ActorMethod<
    [bigint, string, UpdateRepeaterData],
    Repeater
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];